mybatis:
  type-aliases-package: com.dg.pojo
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  page-size-zero: true


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///c2c?serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#  redis:
#    database: 0
#    #host: 119.23.221.110
#    #port: 6379
#    password: 123456
#    timeout: 604800s
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 5
#        min-idle: -1
#    cluster:
#      nodes:
#      - 119.23.221.110:6379
#      - 119.23.221.110:6380
#      - 119.23.221.110:6381
#    sentinel:
#      master: mymaster
#      nodes:
#      - 119.23.221.110:26379

